"""create insurance_plans table

Revision ID: 9da70c255e69
Revises: '8abee965f9c3'
Create Date: 2026-09-19 14:33:59.823503

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9da70c255e69'
down_revision: Union[str, None] = '8abee965f9c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('insurance_plans',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('insurer_id', sa.Integer(), nullable=False),
    sa.Column('plan_name', sa.String(length=255), nullable=False),
    sa.Column('plan_code', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('coverage_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('premium_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('premium_frequency', sa.String(length=50), nullable=False),
    sa.Column('policy_term_years', sa.Integer(), nullable=False),
    sa.Column('eligibility_min_age', sa.Integer(), nullable=True),
    sa.Column('eligibility_max_age', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'ACTIVE', 'INACTIVE', name='plan_status_enum'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['insurer_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_insurance_plans_insurer_id'), 'insurance_plans', ['insurer_id'], unique=False)
    op.create_index(op.f('ix_insurance_plans_plan_code'), 'insurance_plans', ['plan_code'], unique=True)
    op.create_index(op.f('ix_insurance_plans_status'), 'insurance_plans', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_insurance_plans_status'), table_name='insurance_plans')
    op.drop_index(op.f('ix_insurance_plans_plan_code'), table_name='insurance_plans')
    op.drop_index(op.f('ix_insurance_plans_insurer_id'), table_name='insurance_plans')
    op.drop_table('insurance_plans')
    # ### end Alembic commands ###
