"""create insurance_applications table

Revision ID: dda27666620e
Revises: '9da70c255e69'
Create Date: 2026-09-19 15:03:39.218535

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dda27666620e'
down_revision: Union[str, None] = '9da70c255e69'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('insurance_applications',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('insurer_id', sa.Integer(), nullable=False),
    sa.Column('application_number', sa.String(length=100), nullable=False),
    sa.Column('date_of_birth', sa.String(length=50), nullable=False),
    sa.Column('gender', sa.String(length=20), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=False),
    sa.Column('pincode', sa.String(length=20), nullable=False),
    sa.Column('nominee_name', sa.String(length=255), nullable=False),
    sa.Column('nominee_relationship', sa.String(length=100), nullable=False),
    sa.Column('nominee_phone', sa.String(length=50), nullable=False),
    sa.Column('occupation', sa.String(length=100), nullable=False),
    sa.Column('annual_income', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('health_declaration', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('SUBMITTED', 'UNDER_REVIEW', 'APPROVED', 'REJECTED', name='application_status_enum'), nullable=False),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['insurer_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['plan_id'], ['insurance_plans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_insurance_applications_application_number'), 'insurance_applications', ['application_number'], unique=True)
    op.create_index(op.f('ix_insurance_applications_customer_id'), 'insurance_applications', ['customer_id'], unique=False)
    op.create_index(op.f('ix_insurance_applications_insurer_id'), 'insurance_applications', ['insurer_id'], unique=False)
    op.create_index(op.f('ix_insurance_applications_plan_id'), 'insurance_applications', ['plan_id'], unique=False)
    op.create_index(op.f('ix_insurance_applications_status'), 'insurance_applications', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_insurance_applications_status'), table_name='insurance_applications')
    op.drop_index(op.f('ix_insurance_applications_plan_id'), table_name='insurance_applications')
    op.drop_index(op.f('ix_insurance_applications_insurer_id'), table_name='insurance_applications')
    op.drop_index(op.f('ix_insurance_applications_customer_id'), table_name='insurance_applications')
    op.drop_index(op.f('ix_insurance_applications_application_number'), table_name='insurance_applications')
    op.drop_table('insurance_applications')
    # ### end Alembic commands ###
